### ISSUE TITLE
`rust-toolchain.toml` support

### ISSUE THREAD

**Issue by Ch4s3r** [paketo-community/rustup#56]
Would it be possible to support for the [rust-toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)?
This would be quite convenient, as you don't need to specify the options for the toolchain also when running pack.
I have one in my repo already so everybody who checks out that repo does not need to bother with setting the correct settings for their toolchain and also the CI runs the tests with these settings then.
For deploying it would also be awesome to have these settings taken from this standardized file instead of specifying them again in a `project.toml` file.

My `project.toml` looks like this:
```toml
[[build.buildpacks]]
uri = "docker.io/paketocommunity/rust:0.9.0"

[[build.env]]
name = "BP_RUST_PROFILE"
value = "default"

[[build.env]]
name = "BP_RUST_TOOLCHAIN"
value = "nightly"
```

`rust-toolchain.toml`
```toml
[toolchain]
channel = "nightly"
components = ["rustfmt", "clippy"]
profile = "minimal"
```

Yes they diverge, but that's not the point of this ticket 😉
